sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    CACHE_IMAGE: ml4ailab/automates:v2

before_install:
  - docker pull $CACHE_IMAGE
  - docker run -itd --rm --name build-con $CACHE_IMAGE

script:
  - docker exec build-con git fetch
  - docker exec build-con git checkout $TRAVIS_BRANCH
  - if [[ $TRAVIS_BRANCH == "master" ]]; then docker exec build-con git pull; fi
  - if [[ ! $TRAVIS_PULL_REQUEST_BRANCH == "" ]]; then docker exec build-con git pull origin $TRAVIS_PULL_REQUEST_BRANCH; fi
  - docker exec --workdir /automates-v2/docs build-con mkdir -p build
  - docker exec --workdir /automates-v2/docs build-con make apidocs
  - docker exec --workdir /automates-v2/docs build-con make html
  - docker cp build-con:/automates-v2/docs .

deploy:
  local-dir: docs/build/html
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
